const ActionType = {
    SET_INITIAL : 'SET_INITIAL',
    SET_FORM : 'SET_FORM',
    SET_BOOK : 'SET_BOOK',
    SET_LOOK_BOOK : 'SET_LOOK_BOOK',
    SET_ROLLBACK_BOOK : 'SET_ROLLBACK_BOOK',
    SET_HISTORY : 'SET_HISTORY',
    SET_POPULAR_STUDENT_SMK : 'SET_POPULAR_STUDENT_SMK',
    SET_POPULAR_STUDENT_SMA : 'SET_POPULAR_STUDENT_SMA',
    SET_POPULAR_STUDENT_SMP : 'SET_POPULAR_STUDENT_SMP',
    SET_POPULAR_STUDENT_SD : 'SET_POPULAR_STUDENT_SD',
    SET_BANNER : 'SET_BANNER',
}

export default ActionType